dataset:
  target: dataloader.TMRef.TMRefDataset
  params:
    # Path to the file list.
    dataroot: data/datasets/TMGN_1814/train
    scale: 2
    size: 256
    split: "train"
    data_len: -1
    use_cascade: true
    use_txt: true
    txt_level: true
    txt_feature: false

data_loader:
  batch_size: 24
  shuffle: false
  num_workers: 4
  drop_last: false

batch_transform:
  target: dataloader.batch_transform.IdentityBatchTransform
