dataset:
  target: dataloader.TMRef.TMRefCascadeDataset
  params:
    # Path to the file list.
    dataroot: data/datasets/TMGN_1814/val
    datalist: tilelist_18_16_3L.csv
    scale: 2
    size: 256
    split: "test"
    data_len: -1
    use_cascade: true
    use_txt: true
    txt_level: false
    txt_feature: false
    cascade_path: data/exps/refmap-level-train/samples
    #style_path: none

data_loader:
  batch_size: 20
  shuffle: false
  num_workers: 4
  drop_last: false

batch_transform:
  target: dataloader.batch_transform.IdentityBatchTransform
