dataset:
  target: dataloader.TMRef.TMRefCascadeDataset
  params:
    # Path to the file list.
    dataroot: data/datasets/RANGE/LONDON_1814
    datalist: tilelist_18_15_2X_4L80AVG.csv
    scale: 2
    size: 256
    split: "test"
    data_len: -1
    use_cascade: true
    use_txt: true
    txt_level: true
    txt_feature: false
    cascade_path: data/test/refmap-level-test/samples
    #style_path: none

data_loader:
  batch_size: 20
  shuffle: false
  num_workers: 4
  drop_last: false

batch_transform:
  target: dataloader.batch_transform.IdentityBatchTransform
